using System.Text;

namespace Majorsilence.Forms.Migrator;

/// <summary>Renders a human-readable Markdown summary of a migration run.</summary>
internal static class ReportBuilder
{
    public static string Build(
        MigrationOptions options,
        int filesScanned,
        IReadOnlyList<(string Kind, string Path)> changes,
        IReadOnlyList<string> warnings)
    {
        var sb = new StringBuilder();
        sb.AppendLine("# Majorsilence.Forms migration report");
        sb.AppendLine();
        sb.AppendLine($"- **Input:** `{options.Input}`");
        sb.AppendLine($"- **Output:** {(options.Output is null ? "_(in place)_" : $"`{options.Output}`")}");
        sb.AppendLine($"- **Backend:** {options.Backend}");
        sb.AppendLine($"- **Reference mode:** {options.ReferenceMode}");
        sb.AppendLine($"- **Target framework:** {options.TargetFramework ?? "preserve version, drop -windows suffix"}");
        sb.AppendLine($"- **Mode:** {(options.DryRun ? "dry run (no files written)" : "write")}");
        sb.AppendLine();

        sb.AppendLine("## Summary");
        sb.AppendLine();
        sb.AppendLine($"- Files scanned: **{filesScanned}**");
        sb.AppendLine($"- Files changed: **{changes.Count}**");
        sb.AppendLine($"- Manual-review items: **{warnings.Count}**");
        sb.AppendLine();

        sb.AppendLine($"## Changed files ({changes.Count})");
        sb.AppendLine();
        if (changes.Count == 0)
        {
            sb.AppendLine("_None._");
        }
        else
        {
            foreach (var (kind, path) in changes)
                sb.AppendLine($"- `[{kind}]` {path}");
        }
        sb.AppendLine();

        sb.AppendLine($"## Manual review ({warnings.Count})");
        sb.AppendLine();
        if (warnings.Count == 0)
        {
            sb.AppendLine("_Nothing flagged — but a build pass is still recommended._");
        }
        else
        {
            sb.AppendLine("These could not be converted automatically and need a human:");
            sb.AppendLine();
            foreach (var w in warnings)
                sb.AppendLine($"- {w}");
        }
        sb.AppendLine();

        sb.AppendLine("---");
        sb.AppendLine("_Generated by majorsilence-migrate. Review the changes and build before committing._");
        return sb.ToString();
    }
}
